[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
    'prb-math/contracts=lib/prb-math/contracts',
]


# gitmodules version of remappings
# prb-math v2.4.3

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
